sonar.organization=kotenkoigorandr791-afk
sonar.projectKey=kotenkoigorandr791-afk_lab2_public
sonar.projectName=lab2_public

sonar.sourceEncoding=UTF-8

sonar.sources=src/main/java,budget_app-main/src
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.java.source=25
sonar.java.target=25

sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/.vite/**,**/build/**,**/*.scss,**/vite-env.d.ts,**/public/**
sonar.coverage.exclusions=**/*Test.java,**/PasirIhorKotenkoApplicationTests.java,budget_app-main/**/*
sonar.cpd.exclusions=**/dto/**,**/model/**

sonar.typescript.tsconfigPath=budget_app-main/tsconfig.app.json
