spring.application.name=PASiR_Kotenko_Ihor
spring.config.import=optional:file:.env[.properties]

server.port=8081

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3307/${MYSQL_DATABASE:kotenko_ihor}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQL_USER:user-gi}
spring.datasource.password=${MYSQL_PASSWORD:strongUserPass123!}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET:MyVeryLongAndSecurePasirJWTKeyForKotenko2026_AtLeast64Chars_Long_Key}
spring.graphql.path=/graphql
spring.graphql.schema.file-extensions=.graphqls
spring.graphql.graphiql.enabled=true
